# Generated by Django 2.1.4 on 2018-12-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('bill_no', models.BigIntegerField(db_column='BillNo', primary_key=True, serialize=False)),
                ('source', models.CharField(db_column='Source', max_length=50)),
                ('destination', models.CharField(db_column='Destination', max_length=50)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('docket_charges', models.IntegerField(db_column='DocketCharges')),
                ('docket_number', models.BigIntegerField(db_column='DocketNumber')),
                ('company_name', models.CharField(db_column='CompanyName', max_length=100)),
                ('company_address', models.TextField(db_column='CompanyAddress')),
                ('gst_in', models.CharField(db_column='GSTIN', max_length=50)),
                ('shipment_date', models.DateField(db_column='ShipmentDate')),
                ('bill_submission_date', models.DateField(db_column='BillSubmissionDate')),
                ('vehicle_number', models.CharField(db_column='VehicleNumber', max_length=50)),
                ('is_payment_done', models.BooleanField(db_column='IsPaymentDone', default=False, null=True)),
                ('detention_charges', models.IntegerField(db_column='OverHeightCharges')),
                ('over_height_charges', models.IntegerField(db_column='DetentionCharges')),
                ('fov_charges', models.IntegerField(db_column='FOVCharges')),
                ('quantity', models.CharField(db_column='Quantity', max_length=50)),
            ],
            options={
                'db_table': 'bill_detail',
            },
        ),
    ]
