# Generated by Django 2.1.4 on 2018-12-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='fov_charges',
            field=models.IntegerField(db_column='FOVCharges', null=True),
        ),
    ]
