# Generated by Django 2.1.4 on 2018-12-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillWebApp', '0002_auto_20181230_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='CompanyName', max_length=100)),
                ('company_address', models.TextField(db_column='CompanyAddress')),
                ('company_city', models.CharField(db_column='CompanyCity', max_length=100, null=True)),
                ('company_district', models.CharField(db_column='CompanyDistrict', max_length=100, null=True)),
                ('company_gstin', models.CharField(db_column='CompanyGSTIN', max_length=50, null=True)),
                ('company_pincode', models.CharField(db_column='CompanyPinCode', max_length=50, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
