# Generated by Django 2.1.4 on 2019-01-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillWebApp', '0004_auto_20190101_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_city',
            field=models.CharField(blank=True, db_column='CompanyCity', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_district',
            field=models.CharField(blank=True, db_column='CompanyDistrict', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_gstin',
            field=models.CharField(blank=True, db_column='CompanyGSTIN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_pincode',
            field=models.CharField(blank=True, db_column='CompanyPinCode', max_length=50, null=True),
        ),
    ]
